# default target

[build]
target = "riscv32imafc-unknown-none-elf"


[target.riscv32imafc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]


[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "info"
